# Generated by Django 3.1.9 on 2021-06-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclasspassgroup',
            name='archived',
        ),
        migrations.AddField(
            model_name='organizationclasspassgroup',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
