# Generated by Django 3.2.13 on 2022-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=255),
        ),
    ]
