# Generated by Django 2.2.10 on 2020-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclasspass',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='description',
            field=models.TextField(),
        ),
    ]
