# Generated by Django 3.0.8 on 2021-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_squashed_0064_organization_logo_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlogmollie',
            name='log_source',
            field=models.CharField(choices=[('ORDER_PAY', 'Order pay'), ('INVOICE_PAY', 'Invoice pay'), ('WEBHOOK', 'Webhook')], max_length=255),
        ),
    ]
