# Generated by Django 2.1.5 on 2019-02-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoollocation',
            old_name='public',
            new_name='public_item',
        ),
    ]
