# Generated by Django 2.2.8 on 2020-03-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_squashed_0064_auto_20200227_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_insight', 'Can view insight menu'), ('view_insightclasspassesactive', 'Can view insight classpasses active'), ('view_insightclasspassessold', 'Can view insight classpasses sold'), ('view_insightsubscriptionsactive', 'Can view insight subscriptions active'), ('view_insightsubscriptionssold', 'Can view insight subscriptions sold'), ('view_selfcheckin', 'Can use the selfcheckin feature')]},
        ),
    ]
