# Generated by Django 2.2.2 on 2019-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='search_name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
