# Generated by Django 2.2 on 2019-04-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClasspassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClasspassGroupClasspass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_classpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.SchoolClasspass')),
                ('school_classpass_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.SchoolClasspassGroup')),
            ],
        ),
        migrations.AddField(
            model_name='schoolclasspassgroup',
            name='classpasses',
            field=models.ManyToManyField(related_name='classpasses', through='costasiella.SchoolClasspassGroupClasspass', to='costasiella.SchoolClasspass'),
        ),
    ]
