# Generated by Django 2.2.2 on 2019-06-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0002_account_search_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='search_name',
        ),
    ]
