# Generated by Django 3.1.13 on 2021-11-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0002_accountdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdocument',
            name='document',
            field=models.FileField(default=None, upload_to='account_document'),
        ),
    ]
