# Generated by Django 3.1.5 on 2021-01-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0002_auto_20210107_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
