# Generated by Django 2.2.2 on 2019-07-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0002_auto_20190722_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationappointmentprice',
            unique_together={('account', 'organization_appointment')},
        ),
        migrations.RemoveField(
            model_name='organizationappointmentprice',
            name='finance_costcenter',
        ),
        migrations.RemoveField(
            model_name='organizationappointmentprice',
            name='finance_glaccount',
        ),
    ]
