# Generated by Django 3.2.13 on 2022-06-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0002_alter_financeinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightaccountinactive',
            name='count_inactive_accounts',
            field=models.IntegerField(default=0),
        ),
    ]
