# Generated by Django 3.2.12 on 2022-04-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0002_systemmailchimplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='frequency_type',
            field=models.CharField(choices=[('SPECIFIC', 'Specific'), ('WEEKLY', 'Weekly'), ('LAST_WEEKDAY_OF_MONTH', 'Last weekday of month')], max_length=50),
        ),
    ]
