# Generated by Django 2.2 on 2019-04-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0003_organizationlocationroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('display_public', models.BooleanField(default=True)),
                ('display_shop', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('min_duration', models.PositiveIntegerField()),
                ('classes', models.PositiveIntegerField()),
                ('subscription_unit', models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month')], default='DAYS', max_length=10)),
                ('reconciliation_classes', models.PositiveSmallIntegerField()),
                ('credit_validity', models.PositiveIntegerField()),
                ('unlimited', models.BooleanField(default=False)),
                ('terms_and_conditions', models.TextField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quick_stats_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finance_costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceCostCenter')),
                ('finance_glaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount')),
                ('organization_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationMembership')),
            ],
        ),
    ]
