# Generated by Django 3.2.10 on 2022-01-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0003_remove_scheduleitemenrollment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitemenrollment',
            name='account_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='costasiella.accountsubscription'),
        ),
        migrations.AlterField(
            model_name='scheduleitemenrollment',
            name='schedule_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='costasiella.scheduleitem'),
        ),
    ]
