# Generated by Django 2.1.5 on 2019-02-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0003_auto_20190215_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoollocation',
            old_name='public_display',
            new_name='display_public',
        ),
    ]
