# Generated by Django 2.2.10 on 2020-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0003_financeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeorder',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=255),
        ),
    ]
