# Generated by Django 3.1.5 on 2021-02-04 22:39

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0003_auto_20210107_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_email',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_invoice',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_self_checkin',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_shop_header',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='organization'),
        ),
    ]
