# Generated by Django 3.1.13 on 2021-11-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_auto_20211109_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_automation', 'Can view automation menu'), ('view_insight', 'Can view insight menu'), ('view_insightclasspassesactive', 'Can view insight classpasses active'), ('view_insightclasspassessold', 'Can view insight classpasses sold'), ('view_insightsubscriptionsactive', 'Can view insight subscriptions active'), ('view_insightsubscriptionssold', 'Can view insight subscriptions sold'), ('view_insightrevenue', 'Can view insight subscriptions sold'), ('view_selfcheckin', 'Can use the selfcheckin feature')]},
        ),
    ]
