# Generated by Django 3.2.14 on 2022-07-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_auto_20220710_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleeventticket',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='scheduleeventticket',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='scheduleeventticket',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
