# Generated by Django 2.2.10 on 2020-04-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_auto_20200404_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeorder',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='financeorder',
            name='paid',
        ),
    ]
