# Generated by Django 3.2.13 on 2022-04-23 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_accountreportinactive_accountreportinactiveaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightAccountInactiveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='AccountReportInactive',
            new_name='InsightAccountInactive',
        ),
        migrations.DeleteModel(
            name='AccountReportInactiveAccount',
        ),
        migrations.AddField(
            model_name='insightaccountinactiveaccount',
            name='insight_account_inactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='costasiella.insightaccountinactive'),
        ),
    ]
