# Generated by Django 2.2.2 on 2019-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_auto_20190724_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinvoicegroup',
            name='due_after_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='financeinvoicegroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='financeinvoicegroup',
            name='next_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='financeinvoicegroup',
            name='prefix',
            field=models.CharField(default='INV', max_length=255),
        ),
    ]
