# Generated by Django 3.2.10 on 2022-02-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_auto_20220112_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitemattendance',
            name='schedule_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='costasiella.scheduleitem'),
        ),
    ]
