# Generated by Django 3.1.9 on 2021-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_announcement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='OrganizationAnnouncement',
        ),
    ]
