# Generated by Django 2.2 on 2019-04-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_organizationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscriptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='credit_validity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='quick_stats_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='reconciliation_classes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrganizationSubscriptionGroupSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationSubscription')),
                ('organization_subscription_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationSubscriptionGroup')),
            ],
        ),
        migrations.AddField(
            model_name='organizationsubscriptiongroup',
            name='organization_subscriptions',
            field=models.ManyToManyField(related_name='subscriptions', through='costasiella.OrganizationSubscriptionGroupSubscription', to='costasiella.OrganizationSubscription'),
        ),
    ]
