# Generated by Django 3.1.5 on 2021-02-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0004_auto_20210204_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoice',
            name='credit_invoice_for',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
