# Generated by Django 2.2.2 on 2019-06-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_scheduleitemteachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleItemTeachers',
            new_name='ScheduleItemTeacher',
        ),
    ]
