# Generated by Django 3.1.5 on 2021-02-25 18:55

import costasiella.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_financeinvoice_credit_invoice_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('address', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('postcode', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('city', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('country', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('phone', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('mobile', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('registration', models.CharField(default='', max_length=255)),
                ('tax_registration', models.CharField(default='', max_length=255)),
                ('mollie_customer_id', models.CharField(default='', editable=False, max_length=255)),
            ],
        ),
    ]
