# Generated by Django 3.2.10 on 2022-02-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_alter_scheduleitemattendance_schedule_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitemaccount',
            name='schedule_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='costasiella.scheduleitem'),
        ),
    ]
