# Generated by Django 3.1.9 on 2021-06-15 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_auto_20210615_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationannouncement',
            name='date_end',
            field=models.DateField(default=datetime.date(2999, 12, 31)),
            preserve_default=False,
        ),
    ]
