# Generated by Django 2.1.5 on 2019-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_auto_20190301_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClasstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('display_public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
