# Generated by Django 3.2.13 on 2022-05-19 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_auto_20220423_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightaccountinactive',
            name='no_activity_after_date',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
    ]
