# Generated by Django 2.2.2 on 2019-07-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_auto_20190724_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_payment', models.BooleanField(default=False)),
                ('employee_claim', models.BooleanField(default=False)),
                ('account_company', models.CharField(default='', max_length=255)),
                ('account_company_registration', models.CharField(default='', max_length=255)),
                ('account_company_tax_registration', models.CharField(default='', max_length=255)),
                ('account_contact_name', models.CharField(default='', max_length=255)),
                ('account_address', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=255)),
                ('summary', models.CharField(default='', max_length=255)),
                ('invoice_number', models.CharField(default='', max_length=255)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('terms', models.TextField(default='')),
                ('footer', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_invoice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceInvoiceGroup')),
                ('finance_payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinancePaymentMethod')),
            ],
        ),
    ]
