# Generated by Django 3.1.13 on 2021-12-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0005_auto_20211124_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinvoiceitem',
            name='finance_tax_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='costasiella.financetaxrate'),
        ),
    ]
