# Generated by Django 4.0.6 on 2022-07-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_account_invoice_to_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoice',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='costasiella.business'),
        ),
    ]
