# Generated by Django 3.2.10 on 2022-02-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_alter_scheduleitemaccount_schedule_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitemattendance',
            name='account_has_membership',
        ),
    ]
