# Generated by Django 2.2 on 2019-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_organizationsubscriptionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscriptionprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
