# Generated by Django 3.1.9 on 2021-06-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_auto_20210615_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='account_membership',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='costasiella.accountmembership'),
        ),
    ]
