# Generated by Django 2.1.5 on 2019-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_schoolclasstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclasstype',
            old_name='link',
            new_name='url_website',
        ),
        migrations.AlterField(
            model_name='schoolclasstype',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
