# Generated by Django 3.2.13 on 2022-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_alter_insightaccountinactive_no_activity_after_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightaccountinactive',
            name='no_activity_after_date',
            field=models.DateField(),
        ),
    ]
