# Generated by Django 2.2.2 on 2019-07-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_financeinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInvoiceAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceInvoice')),
            ],
        ),
    ]
