# Generated by Django 3.1.5 on 2021-02-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='mobile',
            new_name='phone_2',
        ),
    ]
