# Generated by Django 2.2.10 on 2020-04-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0006_financeorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeorderitem',
            name='organization_classpass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationClasspass'),
        ),
    ]
