# Generated by Django 2.1.5 on 2019-03-14 21:25

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_auto_20190312_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasstype',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='costasiella/media/school_classtype_images'),
        ),
    ]
