# Generated by Django 3.2.13 on 2022-05-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_alter_insightaccountinactive_no_activity_after_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_automation', 'Can view automation menu'), ('view_insight', 'Can view insight menu'), ('view_insightaccountsinactive', 'Can view insight accounts inactive'), ('view_insightclasspasses', 'Can view insight classpasses active'), ('view_insightfinancetaxratesummary', 'Can view insight finance tax rates summary'), ('view_insightrevenue', 'Can view insight subscriptions sold'), ('view_insightsubscriptions', 'Can view insight subscriptions'), ('view_insighttrialpasses', 'Can view insight trial passes'), ('view_selfcheckin', 'Can use the selfcheckin feature')]},
        ),
    ]
