# Generated by Django 3.1.9 on 2021-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_financeinvoiceitem_account_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeatureShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberships', models.BooleanField(default=False)),
                ('subscriptions', models.BooleanField(default=False)),
                ('classpasses', models.BooleanField(default=False)),
                ('classes', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
            ],
        ),
    ]
