# Generated by Django 3.1.5 on 2021-02-25 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_auto_20210225_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='email_billing',
        ),
        migrations.AddField(
            model_name='business',
            name='b2b_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='email_contact',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='business',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='postcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
