# Generated by Django 2.2.2 on 2019-07-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_financeinvoiceamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='account_address',
            new_name='relation_address',
        ),
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='account_company',
            new_name='relation_company',
        ),
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='account_company_registration',
            new_name='relation_company_registration',
        ),
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='account_company_tax_registration',
            new_name='relation_company_tax_registration',
        ),
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='account_contact_name',
            new_name='relation_contact_name',
        ),
    ]
