# Generated by Django 4.0.7 on 2022-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_financeinvoice_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoice',
            name='custom_to',
            field=models.BooleanField(default=False),
        ),
    ]
