# Generated by Django 2.2.10 on 2020-04-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0007_financeorderitem_organization_classpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeorderitem',
            name='schedule_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItem'),
        ),
    ]
