# Generated by Django 2.2.2 on 2019-07-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_accountmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemOrganizationSubscriptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.BooleanField(default=False)),
                ('shop_book', models.BooleanField(default=False)),
                ('attend', models.BooleanField(default=False)),
                ('organization_subscription_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationSubscriptionGroup')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItem')),
            ],
        ),
    ]
