# Generated by Django 2.2.2 on 2019-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_auto_20190726_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinvoiceamount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financeinvoiceamount',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financeinvoiceamount',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financeinvoiceamount',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financeinvoiceamount',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
