# Generated by Django 4.0.7 on 2022-08-23 13:19

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_financeinvoice_custom_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', sorl.thumbnail.fields.ImageField(default=None, upload_to='organization_product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('finance_costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financecostcenter')),
                ('finance_glaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financeglaccount')),
                ('finance_tax_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financetaxrate')),
            ],
        ),
    ]
