# Generated by Django 3.2.13 on 2022-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightaccountinactive',
            name='inactive_accounts_found',
            field=models.IntegerField(null=True),
        ),
    ]
