# Generated by Django 2.1.5 on 2019-03-14 22:03

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_auto_20190314_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasstype',
            name='image_thumbnail_small',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='school_classtype_images'),
        ),
        migrations.AlterField(
            model_name='schoolclasstype',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='school_classtype_images'),
        ),
    ]
