# Generated by Django 3.1.5 on 2021-02-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_auto_20210225_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='b2b_relation',
            new_name='b2b',
        ),
    ]
