# Generated by Django 2.2 on 2019-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0008_auto_20190424_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationsubscriptionprice',
            options={'ordering': ['-date_start']},
        ),
        migrations.AddField(
            model_name='account',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
