# Generated by Django 4.0.7 on 2022-09-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_organizationproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationproduct',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='AccountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('organization_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.organizationproduct')),
            ],
        ),
    ]
