# Generated by Django 2.2.2 on 2019-07-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_auto_20190726_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinvoice',
            name='date_sent',
            field=models.DateField(),
        ),
    ]
