# Generated by Django 3.2.13 on 2022-05-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_insightaccountinactive_inactive_accounts_found'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insightaccountinactive',
            old_name='inactive_accounts_found',
            new_name='count_inactive_accounts',
        ),
    ]
