# Generated by Django 3.1.13 on 2021-12-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_auto_20211207_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitemattendance',
            name='account_classpass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='costasiella.accountclasspass'),
        ),
    ]
