# Generated by Django 2.2.2 on 2019-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_scheduleitemorganizationsubscriptiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_subscription_groups',
            field=models.ManyToManyField(related_name='subscription_groups', through='costasiella.ScheduleItemOrganizationSubscriptionGroup', to='costasiella.OrganizationSubscriptionGroup'),
        ),
    ]
