# Generated by Django 3.1.9 on 2021-07-10 17:24

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_auto_20210710_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
