# Generated by Django 2.2.10 on 2020-04-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0009_auto_20200410_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeorderitem',
            name='finance_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costasiella.FinanceOrder'),
        ),
    ]
