# Generated by Django 3.1.5 on 2021-05-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_financepaymentbatchcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePaymentBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=255)),
                ('status', models.CharField(choices=[('SENT_TO_BANK', 'Sent to Bank'), ('APPROVED', 'Approved'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('REJECTED', 'Rejected')], default='AWAITING_APPROVAL', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('execution_date', models.DateField()),
                ('include_zero_amounts', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_payment_batch_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.financepaymentbatchcategory')),
                ('organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.organizationlocation')),
            ],
        ),
    ]
