# Generated by Django 2.2.10 on 2020-04-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_auto_20200410_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeorder',
            old_name='note',
            new_name='message',
        ),
    ]
