# Generated by Django 3.1.9 on 2021-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_auto_20210710_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlogmollie',
            name='recurring_type',
            field=models.CharField(choices=[('FIRST', 'First'), ('RECURRING', 'Recurring')], max_length=255, null=True),
        ),
    ]
