# Generated by Django 2.2 on 2019-05-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_organizationappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='trashed',
        ),
    ]
