# Generated by Django 2.1.5 on 2019-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_auto_20190314_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceGlaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
