# Generated by Django 3.2.13 on 2022-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_rename_inactive_accounts_found_insightaccountinactive_count_inactive_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightaccountinactive',
            name='count_deleted_inactive_accounts',
            field=models.IntegerField(default=0),
        ),
    ]
