# Generated by Django 2.2.2 on 2019-07-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_auto_20190726_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInvoiceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finance_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceInvoice')),
            ],
        ),
    ]
