# Generated by Django 3.1.13 on 2021-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_auto_20211213_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
