# Generated by Django 4.0.7 on 2022-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0010_alter_organizationproduct_description_accountproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
