# Generated by Django 2.1.5 on 2019-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_financeglaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeglaccount',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
