# Generated by Django 3.1.13 on 2021-12-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_organizationshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.organizationshift'),
        ),
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='organization_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.organizationshift'),
        ),
    ]
