# Generated by Django 2.2.2 on 2019-07-26 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_financeinvoiceaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoice',
            name='accounts',
            field=models.ManyToManyField(related_name='accounts', through='costasiella.FinanceInvoiceAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
