# Generated by Django 3.1.12 on 2021-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_auto_20210722_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
