# Generated by Django 2.2.10 on 2020-04-11 10:18

import costasiella.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_auto_20200410_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=255)),
                ('value', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
            ],
        ),
    ]
