# Generated by Django 3.1.5 on 2021-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_financepaymentbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepaymentbatch',
            name='batch_type',
            field=models.CharField(choices=[('COLLECTION', 'Collection'), ('PAYMENT', 'Payment')], max_length=255),
        ),
    ]
