# Generated by Django 2.2 on 2019-05-16 12:34

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_remove_account_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=costasiella.modules.encrypted_fields.EncryptedCharField(default=None, max_length=255),
        ),
    ]
