# Generated by Django 2.2.2 on 2019-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_scheduleitemorganizationclasspassgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_classpass_groups',
            field=models.ManyToManyField(related_name='classpass_groups', through='costasiella.ScheduleItemOrganizationClasspassGroup', to='costasiella.OrganizationClasspassGroup'),
        ),
    ]
