# Generated by Django 4.0.7 on 2022-09-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0011_alter_accountproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='account_product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='costasiella.accountproduct'),
        ),
    ]
