# Generated by Django 3.1.12 on 2021-08-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0012_organizationlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organization_discovery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='costasiella.organizationdiscovery'),
        ),
        migrations.AddField(
            model_name='account',
            name='organization_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='costasiella.organizationlanguage'),
        ),
    ]
