# Generated by Django 4.0.7 on 2022-10-06 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0012_financeinvoiceitem_account_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_to', models.BooleanField(default=False)),
                ('relation_company', models.CharField(default='', max_length=255)),
                ('relation_company_registration', models.CharField(default='', max_length=255)),
                ('relation_company_tax_registration', models.CharField(default='', max_length=255)),
                ('relation_contact_name', models.CharField(default='', max_length=255)),
                ('relation_address', models.CharField(default='', max_length=255)),
                ('relation_postcode', models.CharField(default='', max_length=255)),
                ('relation_city', models.CharField(default='', max_length=255)),
                ('relation_country', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=255)),
                ('summary', models.CharField(default='', max_length=255)),
                ('quote_number', models.CharField(default='', max_length=255)),
                ('date_sent', models.DateField()),
                ('date_expire', models.DateField()),
                ('terms', models.TextField(default='')),
                ('footer', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='costasiella.business')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceQuoteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('display_public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('next_id', models.PositiveIntegerField(default=1)),
                ('due_after_days', models.PositiveSmallIntegerField(default=30)),
                ('prefix', models.CharField(default='INV', max_length=255)),
                ('prefix_year', models.BooleanField(default=True)),
                ('auto_reset_prefix_year', models.BooleanField(default=True)),
                ('terms', models.TextField(default='')),
                ('footer', models.TextField(default='')),
                ('code', models.CharField(default='', help_text='Journal code in your accounting software.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField(default=0)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('finance_costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financecostcenter')),
                ('finance_glaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financeglaccount')),
                ('finance_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costasiella.financequote')),
                ('finance_tax_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='costasiella.financetaxrate')),
            ],
            options={
                'ordering': ('finance_quote', 'line_number'),
            },
        ),
    ]
