# Generated by Django 2.2.2 on 2019-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0012_scheduleitem_organization_classpass_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAppointmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
