# Generated by Django 2.2.10 on 2020-04-12 12:56

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0012_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mollie_customer_id',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
