# Generated by Django 2.2 on 2019-05-16 13:21

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0012_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=None, max_length=255),
        ),
    ]
