# Generated by Django 3.1.12 on 2021-08-31 10:53

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_auto_20210828_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='key_number',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
