# Generated by Django 2.2.10 on 2020-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_account_mollie_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mollie_customer_id',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
