# Generated by Django 3.1.5 on 2021-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_financepaymentbatch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepaymentbatch',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financepaymentbatch',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
