# Generated by Django 2.2.2 on 2019-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_organizationappointmentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationappointmentcategory',
            name='display_public',
            field=models.BooleanField(default=True),
        ),
    ]
