# Generated by Django 2.1.5 on 2019-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_auto_20190318_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
