# Generated by Django 2.2.2 on 2019-07-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_auto_20190726_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInvoiceGroupDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(default='', max_length=255)),
                ('finance_invoice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceInvoiceGroup')),
            ],
        ),
    ]
