# Generated by Django 2.2 on 2019-05-16 15:06

import costasiella.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0013_auto_20190516_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
