# Generated by Django 3.1.13 on 2021-12-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0014_auto_20211222_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'permissions': [('view_scheduleclass', 'Can view schedule class'), ('add_scheduleclass', 'Can add schedule class'), ('change_scheduleclass', 'Can change schedule class'), ('delete_scheduleclass', 'Can delete schedule class'), ('view_scheduleshift', 'Can view schedule shift'), ('add_scheduleshift', 'Can add schedule shift'), ('change_scheduleshift', 'Can change schedule shift'), ('delete_scheduleshift', 'Can delete schedule shift'), ('view_scheduleappointment', 'Can view schedule appointment'), ('add_scheduleappointment', 'Can add schedule appointment'), ('change_scheduleappointment', 'Can change schedule appointment'), ('delete_scheduleappointment', 'Can delete schedule appointment')]},
        ),
    ]
