# Generated by Django 4.0.7 on 2022-10-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0014_financequote_finance_quote_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financequotegroup',
            old_name='due_after_days',
            new_name='expires_after_days',
        ),
    ]
