# Generated by Django 3.1.12 on 2021-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0014_account_key_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('classes', models.BooleanField(default=False)),
            ],
        ),
    ]
