# Generated by Django 2.1.5 on 2019-03-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0014_financecostcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDiscovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
