# Generated by Django 2.2.2 on 2019-07-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0014_organizationappointmentcategory_display_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationappointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organizationappointment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organizationappointment',
            name='url_website',
        ),
        migrations.AddField(
            model_name='organizationappointment',
            name='organization_appointment_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationAppointmentCategory'),
            preserve_default=False,
        ),
    ]
