# Generated by Django 2.2 on 2019-05-17 07:58

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0014_auto_20190516_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
