# Generated by Django 2.2 on 2019-05-19 07:21

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0015_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='emergency',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
