# Generated by Django 2.2.2 on 2019-07-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0015_auto_20190718_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAppointmentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finance_costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceCostCenter')),
                ('finance_glaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount')),
                ('finance_tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceTaxRate')),
                ('organization_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationAppointment')),
            ],
        ),
    ]
