# Generated by Django 2.2.10 on 2020-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0015_integrationlogmollie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlogmollie',
            name='recurring_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
