# Generated by Django 3.1.12 on 2021-09-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0015_organizationholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationHolidayLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.organizationholiday')),
                ('organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.organizationlocation')),
            ],
        ),
        migrations.AddField(
            model_name='organizationholiday',
            name='organization_location',
            field=models.ManyToManyField(related_name='locations', through='costasiella.OrganizationHolidayLocation', to='costasiella.OrganizationLocation'),
        ),
    ]
