# Generated by Django 3.1.13 on 2021-12-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0015_auto_20211222_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitemweeklyotc',
            options={'permissions': [('view_scheduleclassweeklyotc', 'Can view schedule class & shift weekly one time changes'), ('add_scheduleclassweeklyotc', 'Can add schedule class & shift weekly one time changes'), ('change_scheduleclassweeklyotc', 'Can change schedule class & shift weekly one time changes'), ('delete_scheduleclassweeklyotc', 'Can delete schedule class & shift weekly one time changes')]},
        ),
    ]
