# Generated by Django 2.1.5 on 2019-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0015_schooldiscovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
                ('code', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
