# Generated by Django 2.2.2 on 2019-08-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0016_auto_20190731_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetaxrate',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
