# Generated by Django 2.1.5 on 2019-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0016_financetaxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetaxrate',
            name='tax_type',
            field=models.CharField(choices=[('IN', 'Inclusive'), ('EX', 'Exclusive')], default='IN', max_length=2),
        ),
    ]
