# Generated by Django 2.2 on 2019-06-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0016_auto_20190519_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('CLASS', 'Class'), ('APPOINTMENT', 'Appointment')], max_length=50)),
                ('frequency_type', models.CharField(choices=[('SPECIFIC', 'Specific'), ('WEEKLY', 'Weekly')], max_length=50)),
                ('frequency_interval', models.PositiveSmallIntegerField(choices=[(0, 'Interval unused'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (7, 'Sunday')])),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('public', models.BooleanField(default=False)),
                ('organization_location_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationLocationRoom')),
            ],
        ),
    ]
