# Generated by Django 4.0.7 on 2022-10-17 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0016_systemnotification_systemnotificationaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='accounts',
            field=models.ManyToManyField(related_name='accounts', through='costasiella.SystemNotificationAccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemnotificationaccount',
            name='system_notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notification_accounts', to='costasiella.systemnotification'),
        ),
    ]
