# Generated by Django 3.1.12 on 2021-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0016_auto_20210914_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationholiday',
            name='organization_location',
        ),
        migrations.AddField(
            model_name='organizationholiday',
            name='organization_locations',
            field=models.ManyToManyField(related_name='holidays', through='costasiella.OrganizationHolidayLocation', to='costasiella.OrganizationLocation'),
        ),
    ]
