# Generated by Django 3.1.13 on 2021-12-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0016_auto_20211227_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitemweeklyotc',
            options={},
        ),
    ]
