# Generated by Django 3.1.12 on 2021-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0017_auto_20210914_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_holiday_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_holiday_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationholiday',
            name='classes',
            field=models.BooleanField(default=True),
        ),
    ]
