# Generated by Django 4.0.7 on 2022-10-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0017_systemnotification_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='branding_color_accent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='branding_color_background',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='branding_color_secondary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='branding_color_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
