# Generated by Django 2.2.2 on 2019-08-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0017_auto_20190801_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeinvoice',
            name='accounts',
        ),
        migrations.AddField(
            model_name='financeinvoice',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FinanceInvoiceAccount',
        ),
    ]
