# Generated by Django 3.1.8 on 2021-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0017_auto_20210520_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccount',
            name='holder',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountbankaccount',
            name='number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
