# Generated by Django 2.1.5 on 2019-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0017_financetaxrate_tax_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financetaxrate',
            old_name='tax_type',
            new_name='rate_type',
        ),
    ]
