# Generated by Django 2.2 on 2019-06-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0018_auto_20190605_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='schedule_type',
            new_name='schedule_item_type',
        ),
    ]
