# Generated by Django 3.1.8 on 2021-05-20 12:09

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0018_auto_20210520_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccount',
            name='bic',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='accountbankaccount',
            name='holder',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='accountbankaccount',
            name='number',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default=''),
        ),
    ]
