# Generated by Django 2.2.2 on 2019-08-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0018_auto_20190802_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='account_classpass',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.AccountClasspass'),
        ),
    ]
