# Generated by Django 2.2.2 on 2019-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0019_financeinvoiceitem_account_classpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoice',
            name='relation_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='financeinvoice',
            name='relation_country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='financeinvoice',
            name='relation_postcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
