# Generated by Django 3.1.13 on 2021-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0019_auto_20211007_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfeatureshop',
            name='account_data_download',
            field=models.BooleanField(default=True),
        ),
    ]
