# Generated by Django 2.2 on 2019-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0019_auto_20190605_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
