# Generated by Django 4.0.7 on 2022-11-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0019_alter_accountfinancepaymentbatchcategoryitem_finance_payment_batch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financecostcenter',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financeglaccount',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
