# Generated by Django 3.1.8 on 2021-05-20 13:49

import costasiella.modules.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0019_auto_20210520_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBankAccountMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', costasiella.modules.encrypted_fields.EncryptedTextField(default='19230596-06be-44cf-8fae-1a8975f8b1d1')),
                ('content', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('signature_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='costasiella.accountbankaccount')),
            ],
        ),
    ]
