# Generated by Django 2.1.5 on 2019-03-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0019_schoolmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolmembership',
            name='trial_card',
        ),
        migrations.RemoveField(
            model_name='schoolmembership',
            name='trial_times',
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='display_shop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='terms_and_conditions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='validity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='validity_unit',
            field=models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='finance_glaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount'),
        ),
    ]
