# Generated by Django 4.0.7 on 2022-11-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0020_alter_financecostcenter_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('document', models.FileField(default=None, upload_to='finance_expense')),
                ('finance_costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financecostcenter')),
                ('finance_glaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.financeglaccount')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_expenses', to='costasiella.business')),
            ],
        ),
    ]
