# Generated by Django 2.2 on 2019-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0020_auto_20190606_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='date_end',
            field=models.DateField(default=None, null=True),
        ),
    ]
