# Generated by Django 2.1.5 on 2019-03-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0020_auto_20190327_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmembership',
            name='finance_costcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceCostCenter'),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='finance_glaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount'),
        ),
    ]
