# Generated by Django 2.2.10 on 2020-04-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0020_financeorder_finance_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoicepayment',
            name='online_payment_id',
            field=models.TextField(null=True),
        ),
    ]
