# Generated by Django 3.1.13 on 2021-10-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0020_systemfeatureshop_account_data_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclasspass',
            name='trial_times',
        ),
    ]
