# Generated by Django 3.1.8 on 2021-05-22 09:23

import costasiella.modules.encrypted_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0020_accountbankaccountmandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='460a2094-361e-41db-b5d8-41fce3fe68a6'),
        ),
        migrations.CreateModel(
            name='FinancePaymentBatchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('account_number', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('account_bic', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('mandate_signature_date', models.DateField(null=True)),
                ('mandate_reference', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batch_items', to=settings.AUTH_USER_MODEL)),
                ('account_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.accountsubscription')),
                ('finance_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.financeinvoice')),
                ('finance_payment_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.financepaymentbatch')),
            ],
        ),
    ]
