# Generated by Django 3.1.8 on 2021-05-22 10:10

import costasiella.modules.encrypted_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0021_auto_20210522_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='64d485c8-4d2d-4799-ba4a-5b0dfe3eb764'),
        ),
        migrations.AlterField(
            model_name='financepaymentbatchitem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_batch_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financepaymentbatchitem',
            name='account_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.accountsubscription'),
        ),
    ]
