# Generated by Django 2.2 on 2019-06-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0021_auto_20190606_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'permissions': [('view_schedule_class', 'Can view schedule class'), ('add_schedule_class', 'Can add schedule class'), ('change_schedule_class', 'Can change schedule class'), ('delete_schedule_class', 'Can delete schedule class')]},
        ),
    ]
