# Generated by Django 3.1.13 on 2021-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0021_remove_organizationclasspass_trial_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsubscription',
            name='credit_validity',
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='credit_accumulation_days',
            field=models.PositiveIntegerField(default=31),
        ),
    ]
