# Generated by Django 2.2.10 on 2020-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0021_financeinvoicepayment_online_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoicepayment',
            name='chargeback_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='financeinvoicepayment',
            name='refund_id',
            field=models.TextField(null=True),
        ),
    ]
