# Generated by Django 2.2.2 on 2019-08-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0021_auto_20190802_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='sub_total',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='financeinvoiceitem',
            old_name='sub_total',
            new_name='subtotal',
        ),
        migrations.AlterField(
            model_name='financeinvoiceitem',
            name='finance_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costasiella.FinanceInvoice'),
        ),
    ]
