# Generated by Django 4.0.7 on 2022-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0021_financeexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
