# Generated by Django 2.2.2 on 2019-08-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0022_auto_20190802_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeinvoice',
            old_name='vat',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='financeinvoiceitem',
            old_name='vat',
            new_name='tax',
        ),
    ]
