# Generated by Django 2.2.10 on 2020-04-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0022_auto_20200415_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeinvoicepayment',
            old_name='chargeback_id',
            new_name='online_chargeback_id',
        ),
        migrations.RenameField(
            model_name='financeinvoicepayment',
            old_name='refund_id',
            new_name='online_refund_id',
        ),
    ]
