# Generated by Django 2.2 on 2019-06-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0022_auto_20190606_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'permissions': [('view_scheduleclass', 'Can view schedule class'), ('add_scheduleclass', 'Can add schedule class'), ('change_scheduleclass', 'Can change schedule class'), ('delete_scheduleclass', 'Can delete schedule class')]},
        ),
    ]
