# Generated by Django 3.1.13 on 2021-11-01 13:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0022_auto_20211028_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='account'),
        ),
    ]
