# Generated by Django 4.0.7 on 2022-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0022_financeexpense_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='count_attendance',
            new_name='count_attending',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='count_attending_and_booked',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='count_booked',
            field=models.IntegerField(null=True),
        ),
    ]
