# Generated by Django 3.1.8 on 2021-05-22 10:12

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0022_auto_20210522_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financepaymentbatchitem',
            name='account_subscription',
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='73915713-e1c6-4000-b3bd-d4b658acea4f'),
        ),
    ]
