# Generated by Django 4.0.7 on 2022-12-09 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0023_rename_count_attendance_scheduleitem_count_attending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscriptioncredit',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 12, 56, 58, 538527, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
