# Generated by Django 3.1.8 on 2021-05-22 10:20

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0023_auto_20210522_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='1a3ffa0d-6296-440e-b1b7-245024425801'),
        ),
    ]
