# Generated by Django 2.2 on 2019-06-10 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0023_auto_20190606_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('system_method', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='', help_text='Payment method/condition code in your accounting software.', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financecostcenter',
            name='code',
            field=models.CharField(default='', help_text='Payment method/condition code in your accounting software.', max_length=255),
        ),
    ]
