# Generated by Django 3.1.8 on 2021-05-22 14:02

import costasiella.modules.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0024_auto_20210522_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='65cf1185-a780-4d80-aa04-be1786eaff9a'),
        ),
        migrations.AlterField(
            model_name='financepaymentbatchitem',
            name='finance_payment_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costasiella.financepaymentbatch'),
        ),
    ]
