# Generated by Django 2.2 on 2019-04-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0024_auto_20190410_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasscard',
            name='finance_glaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount'),
        ),
        migrations.AlterField(
            model_name='schoolclasscard',
            name='school_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.SchoolMembership'),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='finance_glaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount'),
        ),
    ]
