# Generated by Django 2.2 on 2019-06-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0024_auto_20190610_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='classtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationClasstype'),
        ),
    ]
