# Generated by Django 2.2.10 on 2020-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0024_systemmailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmailtemplate',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='systemmailtemplate',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
