# Generated by Django 4.0.7 on 2022-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0024_accountsubscriptioncredit_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscriptioncredit',
            name='mutation_amount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=20),
        ),
    ]
