# Generated by Django 2.2.10 on 2020-05-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0025_auto_20200417_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeorderitem',
            old_name='date',
            new_name='attendance_date',
        ),
    ]
