# Generated by Django 2.2.2 on 2019-08-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0025_auto_20190807_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'permissions': [('view_scheduleclass', 'Can view schedule class'), ('add_scheduleclass', 'Can add schedule class'), ('change_scheduleclass', 'Can change schedule class'), ('delete_scheduleclass', 'Can delete schedule class'), ('view_scheduleappointment', 'Can view schedule appointment'), ('add_scheduleappointment', 'Can add schedule appointment'), ('change_scheduleappointment', 'Can change schedule appointment'), ('delete_scheduleappointment', 'Can delete schedule appointment')]},
        ),
    ]
