# Generated by Django 2.2 on 2019-04-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0025_auto_20190410_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolClasscard',
            new_name='SchoolClasspass',
        ),
        migrations.AlterField(
            model_name='schoolclasspass',
            name='finance_glaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount'),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='finance_glaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceGLAccount'),
        ),
    ]
