# Generated by Django 2.2 on 2019-06-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0025_scheduleitem_classtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='classtype',
            new_name='organization_classtype',
        ),
    ]
