# Generated by Django 4.0.7 on 2022-12-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0025_alter_accountsubscriptioncredit_mutation_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsubscription',
            old_name='credit_accumulation_days',
            new_name='credit_validity',
        ),
    ]
