# Generated by Django 3.1.8 on 2021-05-22 14:56

import costasiella.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0025_auto_20210522_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='financepaymentbatch',
            name='count_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financepaymentbatch',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='940e1281-bf3e-4a7b-8a92-0ace9f18a59c'),
        ),
    ]
