# Generated by Django 2.2.10 on 2020-05-05 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0026_auto_20200501_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaccepteddocument',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountclasspass',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classpasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountmembership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financeinvoice',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financeinvoiceitem',
            name='account_classpass',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='costasiella.AccountClasspass'),
        ),
        migrations.AlterField(
            model_name='financeorder',
            name='finance_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='costasiella.FinanceInvoice'),
        ),
    ]
