# Generated by Django 2.2 on 2019-06-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0026_auto_20190611_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='public',
            new_name='display_public',
        ),
    ]
