# Generated by Django 3.1.8 on 2021-05-22 15:01

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0026_auto_20210522_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financepaymentbatch',
            old_name='count_lines',
            new_name='count_items',
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='21a90a3f-3395-4fcc-a4c1-20fd937d589b'),
        ),
    ]
