# Generated by Django 2.2.2 on 2019-08-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0026_auto_20190814_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationAppointment'),
        ),
    ]
