# Generated by Django 3.1.8 on 2021-05-23 12:14

import costasiella.modules.encrypted_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0027_auto_20210522_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='740c1959-1e14-4af4-9930-d3ff1a8794e2'),
        ),
        migrations.CreateModel(
            name='FinancePaymentBatchExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_batch_exports', to=settings.AUTH_USER_MODEL)),
                ('finance_payment_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='costasiella.financepaymentbatch')),
            ],
        ),
    ]
