# Generated by Django 4.0.7 on 2022-12-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0027_accountsubscriptioncredit_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscriptioncredit',
            name='reconciled',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='accountsubscriptioncredit',
            name='schedule_item_attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.scheduleitemattendance'),
        ),
    ]
