# Generated by Django 2.2 on 2019-06-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0027_auto_20190611_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='organization_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationLevel'),
        ),
    ]
