# Generated by Django 2.2.10 on 2020-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0027_auto_20200505_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeorderitem',
            name='attendance_type',
            field=models.CharField(choices=[['CLASSPASS', 'Classpass'], ['SUBSCRIPTION', 'Subscription'], ['COMPLEMENTARY', 'Complementary'], ['REVIEW', 'To be reviewed'], ['RECONCILE_LATER', 'Reconcile later']], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitemattendance',
            name='attendance_type',
            field=models.CharField(choices=[['CLASSPASS', 'Classpass'], ['SUBSCRIPTION', 'Subscription'], ['COMPLEMENTARY', 'Complementary'], ['REVIEW', 'To be reviewed'], ['RECONCILE_LATER', 'Reconcile later']], max_length=255),
        ),
    ]
