# Generated by Django 2.2.2 on 2019-08-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0027_scheduleitem_organization_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='organization_appointment',
        ),
    ]
