# Generated by Django 2.2.10 on 2020-06-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0028_auto_20200604_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('SPECIFIC', 'Specific'), ('WEEKLY', 'Weekly')], max_length=50)),
                ('date', models.DateField(null=True)),
                ('mail_content', models.TextField()),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItem')),
            ],
        ),
    ]
