# Generated by Django 3.1.8 on 2021-05-23 14:29

import costasiella.modules.encrypted_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0028_auto_20210523_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='2eb6ab3f-0c0e-4c6f-a288-0dee5579924f'),
        ),
        migrations.CreateModel(
            name='AccountPaymentBatchCategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batch_category_items', to=settings.AUTH_USER_MODEL)),
                ('finance_payment_batch_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.financepaymentbatchcategory')),
            ],
        ),
    ]
