# Generated by Django 2.2 on 2019-06-12 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0028_scheduleitem_organization_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
