# Generated by Django 2.2.2 on 2019-08-16 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0029_scheduleitemteacheravailable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_has_membership', models.BooleanField(default=False)),
                ('attendance_type', models.CharField(choices=[['TRIAL', 'Trial'], ['DROPIN', 'Drop in'], ['CLASSPASS', 'Classpass'], ['SUBSCRIPTION', 'Subscription'], ['COMPLEMENTARY', 'Complementary'], ['REVIEW', 'To be reviewed'], ['RECONCILE_LATER', 'Reconcile later']], max_length=255)),
                ('date', models.DateField()),
                ('online_booking', models.BooleanField(default=False)),
                ('booking_status', models.CharField(choices=[['BOOKED', 'Booked'], ['ATTENDING', 'Attending'], ['CANCELLED', 'Cancelled']], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account_classpass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.AccountClasspass')),
                ('account_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.AccountSubscription')),
                ('finance_invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.FinanceInvoiceItem')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItem')),
            ],
        ),
    ]
