# Generated by Django 2.2 on 2019-06-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0029_auto_20190612_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('note', models.TextField(default='')),
                ('registration_fee_paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finance_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinancePaymentMethod')),
                ('organization_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationSubscription')),
            ],
        ),
    ]
