# Generated by Django 4.1.4 on 2023-01-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0029_alter_accountsubscriptioncredit_mutation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='info_mail_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
