# Generated by Django 3.1.8 on 2021-05-23 14:40

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0029_auto_20210523_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountPaymentBatchCategoryItem',
            new_name='AccountFinancePaymentBatchCategoryItem',
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='c56a3074-3ac3-4f9f-89b2-4a87ff06f09e'),
        ),
    ]
