# Generated by Django 2.2.10 on 2020-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0029_scheduleitemmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='info_mail_content',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ScheduleItemMail',
        ),
    ]
