# Generated by Django 2.2 on 2019-06-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0030_accountsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='finance_payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinancePaymentMethod'),
        ),
    ]
