# Generated by Django 3.1.8 on 2021-05-28 13:29

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0030_auto_20210523_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financepaymentbatch',
            name='organization_location',
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='fd48c96e-c680-4be8-a55e-0887caf32d8b'),
        ),
    ]
