# Generated by Django 2.2.10 on 2020-06-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0030_auto_20200616_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='info_mail_content',
            field=models.TextField(default=''),
        ),
    ]
