# Generated by Django 2.2.2 on 2019-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0030_scheduleitemattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclasspass',
            name='classes_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
