# Generated by Django 2.2 on 2019-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0031_auto_20190612_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='registration_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
