# Generated by Django 3.0.8 on 2020-08-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0031_scheduleitemweeklyotc_info_mail_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubscriptionCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_type', models.CharField(choices=[('ADD', 'Add'), ('SUB', 'Subtract')], default='ADD', max_length=255)),
                ('mutation_amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('description', models.TextField(default='')),
                ('subscription_month', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.AccountSubscription')),
                ('schedule_item_attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItemAttendance')),
            ],
        ),
    ]
