# Generated by Django 3.1.8 on 2021-06-01 12:40

import costasiella.modules.encrypted_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0031_auto_20210528_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='e8466a98-57b3-4c7a-a2ee-65464691768e'),
        ),
        migrations.CreateModel(
            name='AccountNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backoffice_note', models.BooleanField(default=False)),
                ('teacher_note', models.BooleanField(default=False)),
                ('note', costasiella.modules.encrypted_fields.EncryptedTextField(default='')),
                ('injury', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('note_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
