# Generated by Django 2.2.4 on 2019-08-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0031_accountclasspass_classes_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('MM-DD-YYYY', 'MM-DD-YYYY'), ('DD-MM-YYYY', 'DD-MM-YYYY')], default='YYYY-MM-DD', max_length=255)),
                ('time_format', models.CharField(choices=[('HH:mm', '24 Hr (HH:mm)'), ('hh:mm a', '12 Hr (hh:mm am/pm)')], default='HH:mm', max_length=255)),
            ],
        ),
    ]
