# Generated by Django 4.1.4 on 2023-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0031_scheduleitemweeklyotc_info_mail_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='count_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='enrollment_spaces',
            field=models.IntegerField(default=0, help_text='Number of spaces for enrollments. (Used for enrollments only', null=True),
        ),
    ]
