# Generated by Django 2.2 on 2019-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0032_auto_20190612_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='frequency_interval',
            field=models.IntegerField(choices=[(0, 'Interval unused'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (7, 'Sunday')]),
        ),
    ]
