# Generated by Django 2.2.4 on 2019-08-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0032_appsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSetting',
            new_name='AppSettings',
        ),
    ]
