# Generated by Django 3.0.8 on 2020-08-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0032_accountsubscriptioncredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscriptioncredit',
            name='account_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='costasiella.AccountSubscription'),
        ),
    ]
