# Generated by Django 3.1.8 on 2021-06-01 14:39

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0032_auto_20210601_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountnote',
            options={'permissions': [('view_accountnoteteachers', 'Can view teacher notes'), ('view_accountnotebackoffice', 'Can view backoffice notes')]},
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='9c4ade07-4df6-483b-bdb5-e6395d49dd9a'),
        ),
    ]
