# Generated by Django 2.2.4 on 2019-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0033_auto_20190823_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='time_format',
            field=models.PositiveIntegerField(choices=[(24, '24 Hr (HH:mm)'), (12, '12 Hr (hh:mm am/pm)')], default=24),
        ),
    ]
