# Generated by Django 3.1.8 on 2021-06-01 15:06

import costasiella.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0033_auto_20210601_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountnote',
            name='backoffice_note',
        ),
        migrations.RemoveField(
            model_name='accountnote',
            name='teacher_note',
        ),
        migrations.AddField(
            model_name='accountnote',
            name='note_type',
            field=models.CharField(choices=[('BACKOFFICE', 'Backoffice'), ('TEACHER', 'Teacher')], default='BACKOFFICE', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='78b782c5-d9cc-42d1-bab1-170c15b916a1'),
        ),
    ]
