# Generated by Django 4.1.7 on 2023-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0034_financeexpense_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
    ]
