# Generated by Django 3.0.8 on 2020-08-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0034_auto_20200809_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubscriptionPause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='costasiella.AccountSubscription')),
            ],
        ),
    ]
