# Generated by Django 3.1.8 on 2021-06-01 16:58

import costasiella.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0034_auto_20210601_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='d32471e7-e0ff-48be-ab6e-2e9b260c64b7'),
        ),
        migrations.AlterField(
            model_name='accountnote',
            name='note_type',
            field=models.CharField(choices=[('BACKOFFICE', 'Backoffice'), ('TEACHERS', 'Teachers')], max_length=255),
        ),
    ]
