# Generated by Django 2.2.4 on 2019-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0034_auto_20190825_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='time_format',
            field=models.CharField(choices=[('24', '24 Hr (HH:mm)'), ('12', '12 Hr (hh:mm am/pm)')], default='24', max_length=255),
        ),
    ]
