# Generated by Django 3.1.8 on 2021-06-01 20:10

import costasiella.modules.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0035_auto_20210601_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbankaccountmandate',
            name='reference',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(default='24c4bf7b-fa52-485a-8382-f5132bfd5267'),
        ),
        migrations.CreateModel(
            name='ScheduleEventEarlybird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earlybirds', to='costasiella.scheduleevent')),
            ],
        ),
    ]
