# Generated by Django 3.0.8 on 2020-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0035_accountsubscriptionpause'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscriptionpause',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
