# Generated by Django 4.1.7 on 2023-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0035_financeexpense_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeexpense',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='percentage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='percentage_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='percentage_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
