# Generated by Django 2.2.4 on 2019-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0036_scheduleitemweeklyotc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitemweeklyotc',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitemweeklyotc',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
