# Generated by Django 4.1.7 on 2023-03-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0037_rename_amount_financeexpense_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeexpense',
            old_name='subtotal_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='financeexpense',
            old_name='subtotal_tax',
            new_name='tax',
        ),
    ]
