# Generated by Django 2.2.4 on 2019-08-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0037_auto_20190826_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitemweeklyotc',
            name='display_public',
        ),
    ]
