# Generated by Django 3.0.8 on 2020-08-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0037_accountsubscriptionblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscriptioncredit',
            name='subscription_year',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AccountSubscriptionAltPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_year', models.IntegerField(null=True)),
                ('subscription_month', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_prices', to='costasiella.AccountSubscription')),
            ],
        ),
    ]
