# Generated by Django 3.0.8 on 2020-08-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0038_auto_20200818_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='subscription_unit',
            field=models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month')], default='WEEK', max_length=10),
        ),
    ]
