# Generated by Django 2.2.4 on 2019-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0038_remove_scheduleitemweeklyotc_display_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
