# Generated by Django 2.2.4 on 2019-08-28 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0039_scheduleitemweeklyotc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otc_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='account_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otc_account_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='role',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Subteacher'], ['ASSISTANT', 'Assistant'], ['KARMA', 'Karma']], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='role_2',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Subteacher'], ['ASSISTANT', 'Assistant'], ['KARMA', 'Karma']], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleitemweeklyotc',
            name='organization_classtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.OrganizationClasstype'),
        ),
        migrations.AlterField(
            model_name='scheduleitemweeklyotc',
            name='organization_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.OrganizationLevel'),
        ),
        migrations.AlterField(
            model_name='scheduleitemweeklyotc',
            name='organization_location_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='costasiella.OrganizationLocationRoom'),
        ),
    ]
