# Generated by Django 4.1.7 on 2023-03-14 20:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0039_alter_financeexpense_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpense',
            name='document',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/d/media_protected/', location='/Users/edwin/Developer/costasiella/costasiella/app/costasiella/media_protected'), upload_to='finance_expense'),
        ),
    ]
