# Generated by Django 3.0.8 on 2020-08-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0039_auto_20200822_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeorderitem',
            name='organization_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.OrganizationSubscription'),
        ),
    ]
