# Generated by Django 2.2.4 on 2019-08-28 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0040_auto_20190828_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='si_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='account_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='si_account_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='role',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Subteacher'], ['ASSISTANT', 'Assistant'], ['KARMA', 'Karma']], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='role_2',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Subteacher'], ['ASSISTANT', 'Assistant'], ['KARMA', 'Karma']], default='', max_length=50),
        ),
    ]
