# Generated by Django 3.0.8 on 2020-09-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0040_financeorderitem_organization_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='account_subscription',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='costasiella.AccountSubscription'),
        ),
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='subscription_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='subscription_year',
            field=models.IntegerField(null=True),
        ),
    ]
