# Generated by Django 4.1.9 on 2023-06-21 20:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0040_alter_financeexpense_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdocument',
            name='document',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/d/protected/', location='/home/edwin/Development/costasiella/costasiella/app/costasiella/media_protected'), upload_to='account_document'),
        ),
        migrations.AlterField(
            model_name='financeexpense',
            name='document',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/d/protected/', location='/home/edwin/Development/costasiella/costasiella/app/costasiella/media_protected'), upload_to='finance_expense'),
        ),
    ]
