# Generated by Django 2.2.4 on 2019-08-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0041_auto_20190828_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='role',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='role_2',
        ),
    ]
