# Generated by Django 4.1.9 on 2023-07-07 09:18

import costasiella.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0041_alter_accountdocument_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_automation', 'Can view automation menu'), ('view_insight', 'Can view insight menu'), ('view_insightaccountsinactive', 'Can view insight accounts inactive'), ('view_insightclasspasses', 'Can view insight classpasses active'), ('view_insightfinancetaxratesummary', 'Can view insight finance tax rates summary'), ('view_insightinstructorclassesmonth', 'Can view insight instructor classes in month'), ('view_insightkeynumberswosubscription', 'Can view insight key numbers without subscription'), ('view_insightrevenue', 'Can view insight subscriptions sold'), ('view_insightsubscriptions', 'Can view insight subscriptions'), ('view_insighttrialpasses', 'Can view insight trial passes'), ('view_selfcheckin', 'Can use the selfcheckin feature')]},
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=costasiella.modules.encrypted_fields.EncryptedTextField(data_type='date', default=''),
        ),
    ]
