# Generated by Django 2.2.4 on 2019-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0042_auto_20190828_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='role',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Subteacher'], ['ASSISTANT', 'Assistant'], ['KARMA', 'Karma']], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='role_2',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Subteacher'], ['ASSISTANT', 'Assistant'], ['KARMA', 'Karma']], default='', max_length=50),
        ),
    ]
