# Generated by Django 4.1.10 on 2023-10-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0042_alter_account_options_alter_account_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_automation', 'Can view automation menu'), ('view_insight', 'Can view insight menu'), ('view_insightaccountsinactive', 'Can view insight accounts inactive'), ('view_insightclasspasses', 'Can view insight classpasses active'), ('view_insightfinanceinvoicesopenondate', 'Can view insight finance invoices open on date'), ('view_insightfinancetaxratesummary', 'Can view insight finance tax rates summary'), ('view_insightinstructorclassesmonth', 'Can view insight instructor classes in month'), ('view_insightkeynumberswosubscription', 'Can view insight key numbers without subscription'), ('view_insightrevenue', 'Can view insight subscriptions sold'), ('view_insightsubscriptions', 'Can view insight subscriptions'), ('view_insighttrialpasses', 'Can view insight trial passes'), ('view_selfcheckin', 'Can use the selfcheckin feature')]},
        ),
    ]
