# Generated by Django 2.2.4 on 2019-09-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0043_auto_20190828_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='status',
            field=models.CharField(choices=[['', 'Regular'], ['SUB', 'Sub teacher'], ['CANCELLED', 'Cancelled'], ['OPEN', 'No teacher']], default='', max_length=255),
        ),
    ]
