# Generated by Django 4.1.13 on 2024-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0043_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeorder',
            name='delivery_error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='financeorder',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('DELIVERY_ERROR', 'Delivery Error')], default='RECEIVED', max_length=255),
        ),
    ]
