# Generated by Django 3.0.8 on 2020-10-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0044_scheduleeventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='display_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='display_public',
            field=models.BooleanField(default=False),
        ),
    ]
