# Generated by Django 2.2.4 on 2019-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0045_auto_20190905_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='status',
            field=models.CharField(choices=[['', 'Regular'], ['CANCELLED', 'Cancelled'], ['OPEN', 'No teacher']], default='', max_length=255),
        ),
    ]
