# Generated by Django 2.2.4 on 2019-09-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0046_auto_20190905_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[['TERMS_AND_CONDITIONS', 'Terms and conditions'], ['PRIVACY_POLICY', 'Privacy policy']], max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('document', models.FileField(default=None, upload_to='organization_document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.Organization')),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
    ]
