# Generated by Django 2.2.4 on 2019-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0047_organizationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocument',
            name='version',
            field=models.CharField(default='', max_length=50),
        ),
    ]
