# Generated by Django 3.0.8 on 2020-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0048_auto_20201113_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='spaces',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
