# Generated by Django 3.0.8 on 2020-11-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0049_scheduleitem_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='walk_in_spaces',
            field=models.IntegerField(default=0, help_text="Number of walk-in spaces (Can't be booked online).", null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='spaces',
            field=models.IntegerField(default=0, help_text='Total spaces for this class.', null=True),
        ),
    ]
