# Generated by Django 2.2.4 on 2019-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0050_auto_20190929_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclasspass',
            name='trial_pass',
            field=models.BooleanField(default=False),
        ),
    ]
