# Generated by Django 3.0.8 on 2020-11-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0050_auto_20201114_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='count_attendance',
            field=models.IntegerField(null=True),
        ),
    ]
