# Generated by Django 2.2.4 on 2019-11-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0051_organizationclasspass_trial_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclasspass',
            name='trial_times',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
