# Generated by Django 3.0.8 on 2020-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0051_scheduleitem_count_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='spaces',
            field=models.IntegerField(default=0, help_text='Total spaces for this class.', null=True),
        ),
        migrations.AddField(
            model_name='scheduleitemweeklyotc',
            name='walk_in_spaces',
            field=models.IntegerField(default=0, help_text="Number of walk-in spaces (Can't be booked online).", null=True),
        ),
    ]
