# Generated by Django 2.2.4 on 2019-11-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0052_organizationclasspass_trial_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclasspass',
            name='trial_times',
            field=models.PositiveIntegerField(default=1, help_text='Number of times this pass can be bought by a customer. (Only used when trial card is selected)'),
        ),
    ]
