# Generated by Django 3.0.8 on 2020-11-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0052_auto_20201114_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEventTicketScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_event_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleEventTicket')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItem')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleeventticket',
            name='schedule_items',
            field=models.ManyToManyField(related_name='schedule_items', through='costasiella.ScheduleEventTicketScheduleItem', to='costasiella.ScheduleItem'),
        ),
    ]
