# Generated by Django 3.0.8 on 2020-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0053_auto_20201122_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleeventticketscheduleitem',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
