# Generated by Django 2.2.4 on 2019-11-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0053_auto_20191109_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_classpass_dropin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizationclasspassesdropin', to='costasiella.OrganizationClasspass')),
                ('organization_classpass_trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizationclasspassestrial', to='costasiella.OrganizationClasspass')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleItem')),
            ],
        ),
    ]
