# Generated by Django 2.2.8 on 2019-12-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0054_scheduleitemprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('note', models.TextField(default='')),
                ('finance_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='costasiella.FinanceInvoice')),
                ('finance_payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinancePaymentMethod')),
                ('finance_tax_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.FinanceTaxRate')),
            ],
        ),
    ]
