# Generated by Django 3.0.8 on 2020-11-27 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0054_scheduleeventticketscheduleitem_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountScheduleEventTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled', models.BooleanField(default=False)),
                ('payment_confirmation', models.BooleanField(default=False)),
                ('info_mail_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event_tickets', to=settings.AUTH_USER_MODEL)),
                ('schedule_event_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleEventTicket')),
            ],
        ),
    ]
