# Generated by Django 3.0.8 on 2020-12-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0055_accountscheduleeventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='schedule_event_ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_event_tickets', to='costasiella.AccountScheduleEventTicket'),
        ),
    ]
