# Generated by Django 2.2.8 on 2020-01-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0056_remove_financeinvoicepayment_finance_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinvoiceitem',
            name='line_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
