# Generated by Django 3.0.8 on 2020-12-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0057_auto_20201212_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeinvoiceitem',
            name='schedule_event_ticket',
        ),
        migrations.AddField(
            model_name='financeinvoiceitem',
            name='account_schedule_event_ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='costasiella.AccountScheduleEventTicket'),
        ),
    ]
