# Generated by Django 3.0.8 on 2020-12-26 16:50

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0058_auto_20201218_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEventMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('image', sorl.thumbnail.fields.ImageField(default=None, upload_to='schedule_event_media')),
                ('schedule_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleEvent')),
            ],
        ),
    ]
