# Generated by Django 2.2.8 on 2020-02-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0058_auto_20200103_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_insights', 'Can view insights')]},
        ),
    ]
