# Generated by Django 2.2.8 on 2020-02-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0059_auto_20200214_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_insight', 'Can view insight menu')]},
        ),
    ]
