# Generated by Django 3.0.8 on 2020-12-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0060_auto_20201227_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleeventticket',
            name='schedule_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='costasiella.ScheduleEvent'),
        ),
    ]
