# Generated by Django 2.2.8 on 2020-02-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0060_auto_20200215_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_insight', 'Can view insight menu'), ('view_insightclasspassessold', 'Can view insight classpasses sold')]},
        ),
    ]
