# Generated by Django 2.2.8 on 2020-02-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0062_auto_20200223_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_insight', 'Can view insight menu'), ('view_insightclasspassesactive', 'Can view insight classpasses active'), ('view_insightclasspassessold', 'Can view insight classpasses sold')]},
        ),
    ]
