# Generated by Django 3.0.8 on 2020-12-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0062_auto_20201229_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeorderitem',
            name='schedule_event_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costasiella.ScheduleEventTicket'),
        ),
    ]
