# Generated by Django 2.2.8 on 2020-02-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0063_auto_20200223_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_insight', 'Can view insight menu'), ('view_insightclasspassesactive', 'Can view insight classpasses active'), ('view_insightclasspassessold', 'Can view insight classpasses sold'), ('view_insightsubscriptionsactive', 'Can view insight subscriptions active'), ('view_insightsubscriptionssold', 'Can view insight subscriptions sold')]},
        ),
    ]
