# Generated by Django 3.0.8 on 2021-01-01 19:42

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costasiella', '0063_financeorderitem_schedule_event_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_login',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='organization'),
        ),
    ]
