const cs_local_storage_keys = {
    AUTH_TOKEN: 'costasiella:authToken',
    AUTH_TOKEN_EXP: 'costasiella:authTokenExp',
    AUTH_TOKEN_ORIGIAT: 'costasiella:authTokenorigIat',
    AUTH_TOKEN_REFRESH_EXP: 'costasiella:refreshTokenExp',
    AUTH_LOGIN_NEXT: 'costasiella:authLoginNext',
    FINANCE_INVOICES_FILTER_STATUS: 'costasiella:financeInvoicesFilterStatus',
    FINANCE_INVOICES_EDIT_RETURN: 'costasiella:financeInvoiceEditReturn',
    FINANCE_ORDERS_FILTER_STATUS: 'costasiella:financeOrdersFilterStatus',
    FINANCE_PAYMENT_BATCH_CATEGORIES_SHOW_ARCHIVE: 'costasiella:financePaymentBatchCategoriesShowArchive',
    INSIGHT_CLASSPASSES_YEAR: 'costasiella:insightClasspassesYear',
    INSIGHT_SUBSCRIPTIONS_YEAR: 'costasiella:insightSubscriptionsYear',
    RELATIONS_ACCOUNTS_FILTER_TYPE: 'costasiella:relationsAccountsFilterType',
    RELATIONS_ACCOUNTS_SEARCH: 'costasiella:relationsAccountsSearch',
    RELATIONS_ACCOUNTS_IS_ACTIVE: 'costasiella:relationsAccountsIsActive',
    RELATIONS_ACCOUNT_NOTES_NOTE_TYPE: 'costasiella:relationsAccountNotesNoteType',
    RELATIONS_BUSINESSES_SHOW_ARCHIVE: 'costasiella:relationsBusinessesShowArchive',
    RELATIONS_BUSINESSES_SEARCH: 'costasiella:relationsBusinessesSeach',
    SCHEDULE_APPOINTMENTS_DATE_FROM: 'costasiella:scheduleAppointmentsDateFrom',
    SCHEDULE_APPOINTMENTS_DATE_UNTIL: 'costasiella:scheduleAppointmentsDateUntil',
    SCHEDULE_APPOINTMENTS_ORDER_BY: 'costasiella:scheduleAppointmentsOrderBy',
    SCHEDULE_APPOINTMENTS_FILTER_CLASSTYPE: 'costasiella:scheduleAppointmentsFilterClasstype',
    SCHEDULE_APPOINTMENTS_FILTER_LOCATION: 'costasiella:scheduleAppointmentsFilterLocation',
    SCHEDULE_CLASSES_DATE_FROM: 'costasiella:scheduleClassesDateFrom',
    SCHEDULE_CLASSES_DATE_UNTIL: 'costasiella:scheduleClassesDateUntil',
    SCHEDULE_CLASSES_ORDER_BY: 'costasiella:scheduleClassesOrderBy',
    SCHEDULE_CLASSES_FILTER_CLASSTYPE: 'costasiella:scheduleClassesFilterClasstype',
    SCHEDULE_CLASSES_FILTER_LEVEL: 'costasiella:scheduleClassesFilterLevel',
    SCHEDULE_CLASSES_FILTER_LOCATION: 'costasiella:scheduleClassesFilterLocation',
    SCHEDULE_CLASSES_CLASS_ATTENDANCE_SEARCH: 'costasiella:scheduleClassesClassAttendanceSearch',
    SCHEDULE_EVENTS_ARCHIVED: 'costasiella:scheduleEventsArchived',
    SCHEDULE_EVENTS_TICKETS_CUSTOMERS_SEARCH: 'costasiella:scheduleEventsTicketsCustomersSearch',
    SHOP_CLASSES_DATE_FROM: 'costasiella:shopClassesDateFrom',
    SHOP_CLASSES_DATE_UNTIL: 'costasiella:shopClassesDateUntil',
    SHOP_CLASSES_ORDER_BY: 'costasiella:shopClassesOrderBy',
    SHOP_CLASSES_FILTER_CLASSTYPE: 'costasiella:shopClassesFilterClasstype',
    SHOP_CLASSES_FILTER_LEVEL: 'costasiella:shopClassesFilterLevel',
    SHOP_CLASSES_FILTER_LOCATION: 'costasiella:shopClassesFilterLocation',
}

export default cs_local_storage_keys
